# PyTorch Setup And Installation

## Step 1. Choose PyTorch version
<br>

**CPU Version**: Use this if you don't have a compatible NVIDIA GPU or you don't want to use GPU acceleration. It's a bit easier to set up.
<br>

**GPU Version (CUDA)**: If you have an NVIDIA GPU and want to leverage GPU acceleration for faster training, you'll need the GPU version. Make sure your GPU is CUDA-compatible

## Step 2: Install PyTorch

You can install PyTorch via `pip`. Visit the official PyTorch website (https://pytorch.org/) to find the installation command for your specific configuration. Here's an example of how to install the CPU version:

`pip install torch`

And for the GPU version:

`pip install torch torchvision torchaudio`

## Step 3: Varify the installation 

After installation, you should verify that PyTorch is correctly installed. You can do this by opening a Python interpreter or a Jupyter Notebook and running the following code:

In [1]:
import torch

# Check PyTorch version
print(torch.__version__)

# Check if CUDA (GPU support) is available
print(torch.cuda.is_available())


1.13.1
False


If everything is set up correctly, you should see the PyTorch version and `True` for GPU availability if you installed the GPU version or else `False`.

## Basic Usage of PyTorch Tensors

Now that we have PyTorch installed, let's explore the fundamental data structure of PyTorch: 

### Tensors.

A tensor is similar to a NumPy array but has additional capabilities to accelerate computation. Here's how you can create and work with PyTorch tensors:

In [2]:
# Create a tensor
tensor_a = torch.tensor([1,2,3])
print(tensor_a)

tensor([1, 2, 3])


In [5]:
# Mathematical operation with tensor
tensor_b = torch.tensor([4,5,6])

# Addition
sum_result = tensor_a + tensor_b
sum_result

tensor([5, 7, 9])

In [6]:
# Element-wise Multiplication
multiplication = tensor_a * tensor_b
multiplication

tensor([ 4, 10, 18])

In [8]:
# Matrix-Multiplication (Dot Product)
matrix_a = torch.tensor([[1,2],[3,4]])
matrix_b = torch.tensor([[5,6],[7,8]])

matrix_multi = torch.matmul(matrix_a, matrix_b)
matrix_multi

tensor([[19, 22],
        [43, 50]])

In [10]:
# Tensor Shape and Size
print(tensor_a.shape)       # Shape of 1D tensor
print(matrix_a.shape)       # Shape of 2D tensor

torch.Size([3])
torch.Size([2, 2])


In [14]:
# Converting between NumPy array and PyTorch Tensor
import numpy as np
numpy_array = np.array([1,2,3])
pytorch_tensor = torch.from_numpy(numpy_array)
pytorch_tensor

tensor([1, 2, 3])

In [15]:
# Converting PyTorch array into NumPy array
numpy_array_from_tensor = pytorch_tensor.numpy()
numpy_array_from_tensor

array([1, 2, 3])