# Linear Algebra: Matrix Operation

Linear algebra and matrix operations are fundamental concepts in PyTorch and deep learning. In this explanation, we'll delve deep into matrix operations in PyTorch, covering matrix creation, multiplication, addition, inversion, and more with detailed code examples.

### 1. Matrix Creation
You can create matrices in PyTorch using tensors. Here's how to create matrices with PyTorch.

In [6]:
import torch

# Create a 2x3 matrix
matrix = torch.tensor([[1, 2, 3],[4, 5, 6]])
print(matrix)

# Create identity matrix 3x3
identity_matrix = torch.eye(3)
print(identity_matrix)

# Create a zero matrix 4x2
zero_matrix = torch.zeros(4, 2)
print(zero_matrix)

# Create a random matrix 2x2
random_matrix = torch.rand(2, 2)
print(random_matrix)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.7305, 0.8045],
        [0.9396, 0.8582]])


### 2. Matrix Multiplication

Matrix multiplication is a fundamental operation in linear algebra and deep learning. In PyTorch, you can use the `torch.matmul()` function or the ' `@` ' operator for matrix multiplication.

In [8]:
# Create matrices
ten_a = torch.tensor([[1,2],[3,4]])
ten_b = torch.tensor([[6,7],[8,9]])

# Matrix multiplication using torch.matmul()
mat_mul = torch.matmul(ten_a, ten_b)

# Matrix multiplication using @ operator
mat_mul_at = ten_a @ ten_b
mat_mul, mat_mul_at

(tensor([[22, 25],
         [50, 57]]),
 tensor([[22, 25],
         [50, 57]]))

### 3. Matrix Transpose

Transposing a matrix flips its rows and columns. You can use `torch.transpose()` or the `.t` attribute for transposition.

In [17]:
# Create a Matrix
A = torch.tensor([[1.0, 2.0], [5.0, 6.0]])

# Transpose using torch.transpose()
A_transpose = torch.transpose(A, 0, 1)

# Transpose using .t attribute
transpose_A = A.t()

A_transpose, transpose_A

(tensor([[1., 5.],
         [2., 6.]]),
 tensor([[1., 5.],
         [2., 6.]]))

### 4. Matrix Inversion

To compute the inverse of a matrix, you can use the `torch.inverse()` function. Note that not all matrices have inverses.

In [19]:
# Compute the inverse
A_inverse = torch.inverse(A)
A_inverse

tensor([[-1.5000,  0.5000],
        [ 1.2500, -0.2500]])

### 5. Matrix Determinant

You can calculate the determinant of a square matrix using `torch.det()`.

In [20]:
determinant = torch.det(A)
determinant

tensor(-4.)

# Vectorization

Vectorization is a key concept in PyTorch and deep learning that involves performing operations on entire vectors or matrices at once, rather than using explicit loops. It's essential for efficient numerical computations. In this explanation, we'll delve deep into vectorization in PyTorch, covering its benefits and providing detailed code examples.

### Understanding Vectorization
Vectorization is a technique that allows us to perform operations on entire vectors, matrices, or even higher-dimensional tensors without explicitly writing loops. It leverages low-level optimizations in hardware and libraries to speed up computations significantly. Vectorized code is not only more efficient but also often more concise and readable.

### Benefits of Vectorization
**Efficiency**: Vectorized operations are optimized for parallel processing, making them much faster than equivalent loop-based operations.

**Simplicity**: Vectorized code is often simpler and more readable, reducing the chance of bugs and making the code easier to maintain.

**Portability**: Vectorized operations can be executed on CPUs and GPUs, providing hardware independence.

## Vectorized Operations in PyTorch

PyTorch is designed to work seamlessly with vectorized operations. Here are some common vectorized operations in PyTorch:


### 1. Example: Calculating the Mean of a Large Dataset

Here's an example that demonstrates the efficiency of vectorized operations when calculating the mean of a large dataset:

In [3]:
import time

# Generate a large random dataset
data = torch.randn(1000000)

# Using loops (non-vectorized)
start_time = time.time()
mean_loop = sum(data) / len(data)
loop_time = time.time() - start_time

# Using vectorized operations
v_start_time = time.time()  # Corrected variable name
mean_vectorized = torch.mean(data)
vectorized_time = time.time() - v_start_time

print("Mean (loop):", mean_loop)
print("Mean (vectorized):", mean_vectorized)
print("Time (loop):", loop_time)
print("Time (vectorized):", vectorized_time)

Mean (loop): tensor(-0.0014)
Mean (vectorized): tensor(-0.0014)
Time (loop): 3.159731864929199
Time (vectorized): 0.00028395652770996094


In this example, you'll notice that the vectorized operation is significantly faster, especially with large datasets.