# PyTorch Creation & Manipulation

Tensors are the fundamental building blocks in PyTorch. They are similar to NumPy arrays but come with the added advantage of GPU acceleration for faster numerical computations. In this section, we'll explore various aspects of PyTorch tensors

### 1. Creating Tensors from Data:
You can create PyTorch tensors from Python lists, NumPy arrays, or other Python iterable objects.

In [1]:
import torch

# Creating a tensor from python list
py_list = [1, 2, 3, 4, 5, 6]
tensor_from_list = torch.tensor(py_list)
print(tensor_from_list)

tensor([1, 2, 3, 4, 5, 6])


In [2]:
# Creating a tensor from NumPy array
import numpy as np
num_array = np.array([6,7,8,9])
num_array_to_tensor = torch.tensor(num_array)
print(num_array_to_tensor)

tensor([6, 7, 8, 9])


### 2. Creating Tensors with Specific Values:

You can create tensors with specific values or shapes using functions like `torch.zeros`, `torch.ones`, and `torch.rand`.

In [3]:
# Creating a tensor o zeros
zeros_tensor = torch.zeros(3,2)
print(zeros_tensor)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [4]:
# Creating a tensor of ones
ones_tensor = torch.ones(3,4)
print(ones_tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
# Creating a tensor with random values between 0 and 1
random_tensor = torch.rand(2,2)
print(random_tensor)

tensor([[0.8092, 0.7742],
        [0.3046, 0.0268]])


### 3. Creating Tensors with a Sequence of Numbers:
You can create tensors with sequences of numbers using functions like `torch.arange` and `torch.linspace`.

In [7]:
# Creating a tensor with range of values
range_tensor = torch.arange(0, 10, step=2)
print(range_tensor)

tensor([0, 2, 4, 6, 8])


In [8]:
# Creating a tensor with evenly spaces values
linspace_tensor = torch.linspace(0, 1, steps=5)
print(linspace_tensor)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


# Manipulating Tensors

### 1. Tensor Shape and Size:
You can access the shape and size of a tensor using the `shape` and `size` attributes.

In [10]:
tensor_x = torch.tensor([[1,2,3],[4,5,6]])
print(tensor_x.shape)
print(tensor_x.size())

torch.Size([2, 3])
torch.Size([2, 3])


### 2. Reshaping Tensors:
You can change the shape of a tensor using the `view` method or the `reshape` method.

In [13]:
tensor_y = torch.arange(1,9) #[1, 2, 3, 4, 5, 6, 7, 8]
reshaped_tensor = tensor_y.view(2,4)
reshaped_tensor_z = tensor_y.view(4,2)
print(reshaped_tensor)
print(reshaped_tensor_z)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


### 3. Tensor Slicing and Indexing:
You can access specific elements or sub-tensors within a tensor.

In [15]:
tensor_x = torch.tensor([[1,2,3],[4,5,6]])
print(tensor_x[0,1]) # Accessing the 1st(0th) row and 2nd(1st) column

tensor(2)


In [17]:
# Slicing
print(tensor_x[:, 1:3]) # Get all rows, column 1 ans 2

tensor([[2, 3],
        [5, 6]])


### 4. Element-wise multiplication
PyTorch supports element-wise operations between tensors of the same shape

In [20]:
tensor_a = torch.tensor([1,2,3])
tensor_b = torch.tensor([4,5,6])

# Addition
add = tensor_a + tensor_b
print(add)

# Element-wise multiplication
multiplication = tensor_a * tensor_b
print(multiplication)

# Subtraction
subtraction = tensor_b - tensor_a
print(subtraction)

# Division
division = tensor_b / tensor_a
print(division)

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([3, 3, 3])
tensor([4.0000, 2.5000, 2.0000])


### 5.In-Place Operation

In-place operations modify the tensor directly and are denoted by an underscore at the end of the method name.

In [24]:
tensor = torch.tensor([1,2,3])
tensor.add_(5) # Add 5 to each element of tensor
print(tensor)

tensor([6, 7, 8])


### 6. Concatenating Tensors

You can concatenate tensors along specified dimensions using `torch.cat`.

In [29]:
tensor_a = torch.tensor([[1,2], [3,4]])
tensor_b = torch.tensor([[5,6], [7,8]])

# Concatenating along rows (dimension 0)
concatenated_tensor = torch.concat((tensor_a, tensor_b), dim=0)
print(concatenated_tensor)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [30]:
# Concatenating along rows (dimension 1)
concatenated_tensor = torch.concat((tensor_a, tensor_b), dim=1)
print(concatenated_tensor)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
