# PyTorch Creation & Manipulation

Tensors are the fundamental building blocks in PyTorch. They are similar to NumPy arrays but come with the added advantage of GPU acceleration for faster numerical computations. In this section, we'll explore various aspects of PyTorch tensors

### 1. Creating Tensors from Data:
You can create PyTorch tensors from Python lists, NumPy arrays, or other Python iterable objects.

In [1]:
import torch

# Creating a tensor from python list
py_list = [1, 2, 3, 4, 5, 6]
tensor_from_list = torch.tensor(py_list)
print(tensor_from_list)

tensor([1, 2, 3, 4, 5, 6])


In [2]:
# Creating a tensor from NumPy array
import numpy as np
num_array = np.array([6,7,8,9])
num_array_to_tensor = torch.tensor(num_array)
print(num_array_to_tensor)

tensor([6, 7, 8, 9])


### 2. Creating Tensors with Specific Values:

You can create tensors with specific values or shapes using functions like `torch.zeros`, `torch.ones`, and `torch.rand`.

In [3]:
# Creating a tensor o zeros
zeros_tensor = torch.zeros(3,2)
print(zeros_tensor)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [4]:
# Creating a tensor of ones
ones_tensor = torch.ones(3,4)
print(ones_tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
# Creating a tensor with random values between 0 and 1
random_tensor = torch.rand(2,2)
print(random_tensor)

tensor([[0.8092, 0.7742],
        [0.3046, 0.0268]])


### 3. Creating Tensors with a Sequence of Numbers:
You can create tensors with sequences of numbers using functions like `torch.arange` and `torch.linspace`.

In [7]:
# Creating a tensor with range of values
range_tensor = torch.arange(0, 10, step=2)
print(range_tensor)

tensor([0, 2, 4, 6, 8])


In [8]:
# Creating a tensor with evenly spaces values
linspace_tensor = torch.linspace(0, 1, steps=5)
print(linspace_tensor)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
